name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/c6bd06256dd700a45e483869bcdcf304239393a6/scripts/download-actionlint.bash) 1.6.27
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} -color
        shell: bash

  build-lint-test:
    name: Build, lint, and test
    uses: ./.github/workflows/build-lint-test.yml

  all-jobs-complete:
    name: All jobs complete
    runs-on: ubuntu-latest
    needs:
      - check-workflows
      - build-lint-test
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-complete
    steps:
      - name: Check that all jobs have passed
        run: |
          passed="${{ needs.all-jobs-complete.outputs.PASSED }}"
          if [[ $passed != "true" ]]; then
            exit 1
          fi

  is-release:
    name: Determine whether this is a release merge commit
    needs: build-lint-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    steps:
      - id: is-release
        uses: MetaMask/action-is-release@v2
        with:
          commit-starts-with: 'Release [version],Release/[version]'

  publish-release:
    name: Publish release
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
