name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-release:
    name: Publish release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - name: Create build cache
        uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            ./packages/**/dist
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
      - name: Publish release to GitHub
        uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Yarn dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build

  publish-npm-dry-run:
    name: Dry run publish to npm
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Restore build cache
        uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            ./packages/**/dist
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
          fail-on-cache-miss: true
      - name: Dry run publish
        # Omit npm-token token to perform a dry run.
        uses: MetaMask/action-npm-publish@v5
        env:
          SKIP_PREPACK: true

  publish-npm:
    name: Publish to npm
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ./packages/**/dist
            ./node_modules/.yarn-state.yml
          key: ${{ github.sha }}
          fail-on-cache-miss: true
      - name: Publish
        uses: MetaMask/action-npm-publish@v5
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true

  publish-docs:
    name: Publish docs
    needs: publish-npm
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-docs.yml
